backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "المقالات"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "string" }
      - { label: "التاريخ", name: "pubDate", widget: "datetime" }
      - { label: "المؤلف", name: "author", widget: "string" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
